### ISSUE TITLE
Quirrel dev server runtime error after running for several minutes

### ISSUE THREAD

**Issue by bardsol** [quirrel-dev/quirrel#452]
This has happened a few times when I leave the server running.

## Bug Report

**Current Behavior**
Leaving Quirrel dev server running for several minutes

**Input Code**
concurrently 'next dev' 'quirrel'

**Expected behavior/code**
Server keeps running.

**Environment**

- Quirrel version: 1.5.0
- Node/npm version: Node 15.12.0/NPM 7.9.0

**Additional context/Screenshots**
[1] This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
[1] TypeError: Cannot read property 'split' of undefined
[1]     at StaleChecker.parseJobDescriptor (/Users/bsolvang/Documents/SandeFredin/clients/klinikk.no/node_modules/@quirrel/owl/dist/shared/stale-checker.js:98:29)
[1]     at Array.map (<anonymous>)
[1]     at StaleChecker.<anonymous> (/Users/bsolvang/Documents/SandeFredin/clients/klinikk.no/node_modules/@quirrel/owl/dist/shared/stale-checker.js:126:117)
[1]     at step (/Users/bsolvang/Documents/SandeFredin/clients/klinikk.no/node_modules/@quirrel/owl/dist/shared/stale-checker.js:33:23)
[1]     at Object.next (/Users/bsolvang/Documents/SandeFredin/clients/klinikk.no/node_modules/@quirrel/owl/dist/shared/stale-checker.js:14:53)
[1]     at fulfilled (/Users/bsolvang/Documents/SandeFredin/clients/klinikk.no/node_modules/@quirrel/owl/dist/shared/stale-checker.js:5:58)
[1]     at runNextTicks (node:internal/process/task_queues:59:5)
[1]     at listOnTimeout (node:internal/timers:526:9)
[1]     at processTimers (node:internal/timers:500:7)

**Comment by Skn0tt** [comment]
Hi @bardsol! This is an interesting defect. Looking at the stacktrace, it orginates from [Owl](https://github.com/quirrel-dev/owl)'s stale-checker. I'll take a stab at fixing this later today.

My suspicion is that you have a long-running job that's deleted between *start* and *end* of execution. Is this the case? If not, could you briefly describe what kind of job this occurs with and how it's being executed? This is helpful for a regression test :)

**Comment by Skn0tt** [comment]
Took a closer look now, and I fail reproducing this. Could you supply a reproduction repo? If it's okay for you, you can also reach out via email and send me a zip of your project.

**Comment by bardsol** [comment]
Hey @Skn0tt! I actually just have the server running and I haven't enabled any quirrel jobs yet. So it's basically failing without me doing anything. But it takes some time - probably over 30 minutes before this happens.

I'm sorry I don't have any available repo to share to reproduce this.

Could the error lie within the fact that there are no jobs?

**Comment by Skn0tt** [comment]
If you don't do nothing and there are no jobs (maybe auto-registered cron jobs?), it fails after roughly 30 minutes ... Well that's interesting behaviour 🤔 I'll look into it, but it can take a while. Is this a high-priority bug for you right now?

**Comment by lopermo** [comment]
![Screenshot 2021-06-11 at 11 44 46](https://user-images.githubusercontent.com/11388254/121667345-79b3a700-caaa-11eb-95be-f386e91e8398.png)
Same going on here

I just launched it as `npx quirrel` and had it idle for some time

**Comment by Skn0tt** [comment]
This is a really interesting issue! [`ioredis-mock`](https://github.com/stipsan/ioredis-mock) seems to have a bug where it returns `undefined` instead of a string. Pretty close to solving this one :)

**Comment by Skn0tt** [comment]
released in v1.6.2
